import { Poppins } from "next/font/google";
import "./globals.css";
import TanstackQueryProvider from "./_libs/components/providers/TanstackQueryProvider";

const font = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Car Rental Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main>
          <TanstackQueryProvider>
            <div className="bg-white">{children}</div>
          </TanstackQueryProvider>
        </main>
      </body>
    </html>
  );
}
